environment:
  TEST_VAL=42
ready_wait:
  15
context_path:
  ./src/docker
domains: deploylink.com
dockerfileonly: true
compose_files:
  docker_b:
    filename:
      ./src/docker/DockerfileB
    domains: deployrun.com
    context_path:
      ./src/docker
  docker_c:
    filename:
      ./src/docker/DockerfileC
    domains: testdeploy.io
    context_path:
      ./src/docker
